### PR TITLE
fix: add footer to results page

### LINKED ISSUE #75: Bring back footer in `INFO-end` view
As of now, we're hiding the Footer on the results view  because of #25
Is there a way we can bring these back?
(@toto04 it had something to do with the navigation, but since @lorenzocorallo has fixed a lot of those issues we may be good to bring those back 🤷🏻‍♂️)

### PR DESCRIPTION
**Pull request by lorenzocorallo**
Changes

- Make footer visible on results page
- Simplified routes structure: test and results page are on their own pathname correctly (`/test`, `/results`), leaving index only for Home
- InfoView folder and file are not needed anymore
  - `InfoView/InfoStart.tsx` moved to `pages/Home.tsx`
  - `InfoView/InfoEnd.tsx`moved to `pages/Results.tsx`
  - `InfoView/InfoView.tsx` deleted
- Implemented navigation blocking in results page: until the user click on the save button, a prompt asks confirmation to exit that page (#73 applies here too)
- Moved `view` type definition to `constants` and made PascalCase for consistency
- Renamed view `INFO-end` to `TOL-end` because otherwise it was causing some unexpected behaviour when redirecting from test page to results page (blank screen, redirect to home, ...)
- `<Link>` in footer have `replace` attribute pointed to a calculated value, based on `location.pathname`, so that when the user changes page from the results one, the user cannot go back
- When the view changes from `TOL-*` to `INFO-start`, `App.tsx` states (including questions, answers and time record) are cleared and questions are re-generated, so that a new test is possible; before this was handled via page reload, but now it can support internal page switching and the new results page behaviour
- `window.onbeforeunload` event handlers are moved from `App.tsx` to `Results.tsx` and `QuestionForm.tsx`, because those are the only pages which require it and it's also possible to set the correct prompt message depending on the situation

Closes #75

### CODE REVIEW

File: src/components/pages/Results.tsx [hunk 1]
```diff
@@ -74,8 +81,34 @@ const styles = StyleSheet.create({
 interface InfoEndProps {
   answers: AnswersData
   questions: QuestionsData
+  viewState: statePair<View>
 }
 export default function InfoEnd(props: InfoEndProps) {
```
Comment (EndBug) [inline src/components/pages/Results.tsx:86]: This is a real nitpick, but we should rename `InfoEnd` to `Restults` and `InfoEndProps` to `ResultsProps` 🙃

File: src/components/pages/Results.tsx [hunk 2]
```diff
@@ -74,8 +81,34 @@ const styles = StyleSheet.create({
...
+  const [isResultSaved, setIsResultSaved] = useState(false)
+  const blocker = useBlocker(!isResultSaved)
+
+  const navigate = useNavigate()
+  const handleNewTest = () => {
+    navigate('/', { replace: true })
+  }
+
+  const exit_warn = 'Non hai salvato i tuoi risultati. Sicuro di voler uscire?'
```
Comment (EndBug) [inline src/components/pages/Results.tsx:95]: Can make this using i18n as well?

File: src/components/pages/Results.tsx
Comment (EndBug) [inline src/components/pages/Results.tsx:1]: We left the "InfoEnd", now "Results" page in Italian-only as if it was part of the test. I think we should translate it using i18n too: an international student might appreciate having this page in English too.

File: src/components/pages/Results.tsx [hunk 3]
```diff
@@ -242,11 +276,9 @@ export default function InfoEnd(props: InfoEndProps) {
             test, o andranno persi!
           </h3>
           <Button
-            label="Inizia un nuovo test"
+            label="Torna alla home"
```
Comment (EndBug) [inline src/components/pages/Results.tsx:279]: Last i18n comment for the file 🙃

**Review by EndBug — CHANGES_REQUESTED** [review]
Awesome work, as always 🌟 

I have just a couple of nitpicks, but I have to say that you really did a great job with the whole navigation system, it was really aweful before ahahhahah

File: src/locales/en.json [hunk 4]
```diff
@@ -21,5 +21,32 @@
...
+    "tableHeader2": "Num. of questions",
+    "tableHeader3": "Correct",
+    "tableHeader4": "Wrong",
+    "tableHeader5": "Not given",
+    "pointsCalcTitle": "How the score is calculated",
+    "pointsCalcBody1": "The <strong>maximum achievable score</strong> <strong>is {{v1}} </strong> and is expressed to the second decimal place. <br /> The attribution of <strong>OFA TEST</strong> (Obblighi Formativi Aggiunti) occurs when the test score, rounded to the nearest integer, <strong>is less than {{v2}}</strong>.<br /> The attribution of <strong>OFA TENG</strong> occurs when, considering only the {{v3}} section, the number of correct answers <strong>is less than {{v4}}</strong>. <br />",
+    "pointsCalcUl1": "The test <strong>score</strong> is calculated by assigning:",
+    "pointsCalcItem1": "{{v}} point for each correct answer",
+    "pointsCalcItem2": "{{v}} point for each wrong answer",
+    "pointsCalcItem3": "{{v}} point for each answer not given",
```
Comment (EndBug) [inline src/locales/en.json:40]: It currently says "-0,25 point" and "0 point"

The lazy way to fix this would be changing the translation like this:
```suggestion
    "pointsCalcItem1": "{{v}} point for each correct answer",
    "pointsCalcItem2": "{{v}} points for each wrong answer",
    "pointsCalcItem3": "{{v}} points for each answer not given",
```

If we want to do it properly, we'd need a way to dynamically change between the singular and plural form, depedening on whether the value is `1`.
That would need to apply to the Italian version as well.

File: src/locales/en.json [hunk 5]
```diff
@@ -21,5 +21,32 @@
...
+    "pointsCalcUl2": "and assigning a weight of",
+    "pointsCalcItem4": " for each question of {{sec}}",
+    "pointsCalcBody2": "The <strong>total score</strong> is rounded to the nearest integer (ex: score 59.49 is rounded to 59, score 59.50 to 60)",
```
Comment (EndBug) [inline src/locales/en.json:43]:
```suggestion
    "pointsCalcBody2": "The <strong>total score</strong> gets rounded to the nearest integer (e.g., 59,49 gets rounded to 59, while 59,50 to 60)",
```

To be honest, I'd prefer using `.` as the decimal separator as well, but I feel it would clash with the other parts of the test.

File: src/locales/en.json [hunk 6]
```diff
@@ -21,5 +21,32 @@
   },
   "privacy": {
     "localStorage": "This website uses the browser <link /> to save user preferences, for example the test mode (regular or DSA) or the website language. These settings are never sent to any server, instead they are handled locally by the browser. Moreover, preferences are deleted after 6 months from the last change."
+  },
+  "results": {
+    "exitWarn": "You did not save your results. Are you sure to exit?",
```
Comment (EndBug) [inline src/locales/en.json:26]:
```suggestion
    "exitWarn": "You did not save your results. Are you sure you want to exit?",
```

File: src/components/ExtendCorrection/ExtendedCorrection.tsx [hunk 7]
```diff
@@ -138,28 +134,31 @@ const PrintDocument = forwardRef<HTMLDivElement, ExtendedCorrectionProps>(
...
     const { resultTable, questions, answers } = props
+    const { t, i18n } = useTranslation()
+
     return (
       <div className="print-only" ref={ref} style={styles.doc}>
         <div style={docStyles.firstPage}>
           <DocumentHeader />
-          <p style={styles.centered}>Simulazione del {dateTime}</p>
+          <p style={styles.centered}>
+            <Trans i18n={i18n} values={{ date: dateTime }}>
```
Comment (EndBug) [inline src/components/ExtendCorrection/ExtendedCorrection.tsx:144]: `dateTime` is a string containing `"alle"`, in Italian
I suggest we split this in `date` and `time`, and use two different values in the translation, so that we can use `"at"` in the English version

File: src/locales/en.json [hunk 8]
```diff
@@ -21,5 +21,32 @@
...
+    "pointsCalcItem3": "{{v}} point for each answer not given",
+    "pointsCalcUl2": "and assigning a weight of",
+    "pointsCalcItem4": " for each question of {{sec}}",
+    "pointsCalcBody2": "The <strong>total score</strong> is rounded to the nearest integer (ex: score 59.49 is rounded to 59, score 59.50 to 60)",
+    "saveReminder": "Remember to save your results before starting a new test, or they will be lost!",
+    "homeBtn": "Go back to home",
+    "saveBtn": "Save test results",
+    "pdfTitle": "Simulation of {{- date}}",
+    "pdfInfo1": "Do you have questions about the questions and their resolution? Ask them on the ",
+    "tgGroup": "TOL Prepration Group of PoliNetwork",
```
Comment (EndBug) [inline src/locales/en.json:49]:
```suggestion
    "tgGroup": "PoliNetwork's TOL Prepration Group",
```

File: src/locales/en.json [hunk 9]
```diff
@@ -21,5 +21,32 @@
...
+    "pointsCalcItem2": "{{v}} point for each wrong answer",
+    "pointsCalcItem3": "{{v}} point for each answer not given",
+    "pointsCalcUl2": "and assigning a weight of",
+    "pointsCalcItem4": " for each question of {{sec}}",
+    "pointsCalcBody2": "The <strong>total score</strong> is rounded to the nearest integer (ex: score 59.49 is rounded to 59, score 59.50 to 60)",
+    "saveReminder": "Remember to save your results before starting a new test, or they will be lost!",
+    "homeBtn": "Go back to home",
+    "saveBtn": "Save test results",
+    "pdfTitle": "Simulation of {{- date}}",
+    "pdfInfo1": "Do you have questions about the questions and their resolution? Ask them on the ",
```
Comment (EndBug) [inline src/locales/en.json:48]:
```suggestion
    "pdfInfo1": "Do you have any doubts about the questions and their resolution? Ask on the ",
```

**Review by EndBug — CHANGES_REQUESTED** [review]
Sorry eheh, still a couple of nitpicks
image

**Review by EndBug — APPROVED** [review]
Love it! ❤️
