### PR TITLE
fix: remove PanelBear

### LINKED ISSUE #74: Remove PanelBear
We should unlink the website from our PanelBear account and remove any references to it, since they're shutting down in May.

### PR DESCRIPTION
**Pull request by lorenzocorallo**
- Locales definitions and strings referring to the tracker weren't removed, but the corresponding text is hidden in the Privacy page until the tracker is replaced and the links changed
- `@panelbear` packages are removed with all the references in the `src`
- Left comments where the previously tracker was used, so that it's easier to replace it

Closes #74

### CODE REVIEW

File: src/components/InfoView/InfoView.tsx [hunk 1]
```diff
@@ -29,7 +28,8 @@ export default function InfoView(props: InfoViewProps) {
       startTest={() => {
         setView('TOL-testing')
         navigate('/test')
-        PanelBear.track('TestStart')
+        // insert new tracker here
+        // .track('TestStart')
```
Comment (EndBug) [inline src/components/InfoView/InfoView.tsx:32]:
```suggestion
```

Let's just remove these lines, we don't know how the next tracker will be implemented.

File: src/components/QuestionsForm/QuestionsForm.tsx [hunk 2]
```diff
@@ -188,7 +187,8 @@ export default function QuestionsForm(props: QuestionsFormProps) {
             } else {
               setView('INFO-end')
               navigate('/results', { replace: true })
-              PanelBear.track('ViewResults')
+              // insert new tracker here
+              // .track('ViewResults')
```
Comment (EndBug) [inline src/components/QuestionsForm/QuestionsForm.tsx:191]:
```suggestion
```

File: src/components/pages/Privacy.tsx [hunk 3]
```diff
@@ -20,26 +20,26 @@ function Link({
...
+              i18n={i18n}
+              components={{
+                link: components.trackerLink
+              }}
+            >
+              privacy.tracker
+            </Trans>
+          </p>
+        )
+      }
```
Comment (EndBug) [inline src/components/pages/Privacy.tsx:42]: Let's just remove this altogether as well

**Review by EndBug — CHANGES_REQUESTED** [review]
IMO it's better if we just remove everything, without commenting out stuff: it's just cleaner, and we make sure we don't leave anything behind
We can always look back at the history if we want to see how we used to track stuff

I've added a couple of comments, but it's better if we also check the rest

**Review by EndBug — APPROVED** [review]
Thanks 🫶🏻
